language: r
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
      - valgrind

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install --yes libjq-dev libprotobuf-dev libprotoc-dev protobuf-compiler

sudo: required

dist: trusty

warnings_are_errors: true

r_packages:
  - sp
  - rgdal
  - rgeos
  - roxygen2
  - rmarkdown
